# Generated by Django 4.1.3 on 2022-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=20)),
                ('laqabi', models.CharField(max_length=10)),
                ('yoshi', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=10)),
                ('rangi', models.CharField(max_length=10)),
                ('hidi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Institut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shahar', models.CharField(max_length=10)),
                ('yonalish', models.CharField(max_length=20)),
                ('kurs', models.IntegerField(default=4)),
            ],
        ),
    ]
