# Generated by Django 4.1.3 on 2022-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(max_length=20)),
                ('narxi', models.IntegerField(default=10)),
                ('rangi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Davlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('aholisi', models.IntegerField(default=10)),
                ('poytaxt', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kompyuter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('versiyasi', models.IntegerField(default=10)),
                ('narxi', models.IntegerField(default=10)),
            ],
        ),
    ]
